### ISSUE TITLE
Add desktop file 

### ISSUE THREAD

**Issue by kikislater** [bartoszek/AUR-cloudcompare#1]
There is no .desktop or other in this package so application is not present in menu. A kind of this =>

File : /usr/share/applications/cloudcompare.desktop

> [Desktop Entry]
> Type=Application
> Name=CloudCompare
> Comment=CloudCompare
> Exec=/usr/bin/CloudCompare
> Icon=#Add Icon.png (remove hashtag to get it work)
> Terminal=false
> Categories=Qt;Education;

**Comment by bartoszek** [comment]
Thanks, you just made my morning hours invested of bash scripting not wasteful after all  :blush:
