### ISSUE TITLE
Freeze submodule commit

### ISSUE THREAD

**Issue by AchmadFathoni** [bartoszek/AUR-cloudcompare#19]
I'm not so sure, but here is what I understand.

Every time cloudcompare sub-module dependency get new commit. It will makes updating AUR with yay to rebuild the cloudcomapre package. 

My personal opinion:

This is stable cloudcompare and not cloudcompare-git, we should freeze the commit version of cloudcompare sub-module so it's not get rebuild so often. Freezing commit will also makes cloudcomapre more stable. After all cloudcompare takes long time to build. At least in my computer. Somethign like

```
source=(
    "git+:git+https://github.com/asmaloney/libE57Format#commit=787259b"
}
```
Here is an [example](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=xgboost) from my xboost package that use froozen sub-modules commit versin.

**Comment by petronny** [comment]
Hi, [arch4edu](https://github.com/arch4edu/arch4edu) starts to provide the binary of this package now.

Installing it from a repository may disable the VCS detection of yay.
